---
- name: add software-properties-common repo
  apt: pkg=software-properties-common state=present update_cache=yes

- name: add python-software-properties repo
  apt: pkg=python-software-properties state=present update_cache=yes
  when: ansible_distribution_release == "precise"

- name: add webupd8 ppa to get java
  apt_repository: repo='ppa:webupd8team/java'

- name: update apt cache
  apt: update_cache=yes

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: install java8
  shell: apt-get install -y oracle-java8-installer
