---
- name: add add-apt-repostory 'software-properties-common'
  apt: pkg=software-properties-common state=present update_cache=yes
  sudo: yes 

- name: add add-apt-repostory 'python-software-properties'
  apt: pkg=python-software-properties state=present update_cache=yes
  sudo: yes 
  when: ansible_distribution_release == "precise"

- name: add webupd8 ppa to get java
  apt_repository: repo='ppa:webupd8team/java'

- name: update apt cache
  shell: apt-get update
  sudo: yes

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes

- name: install java8
  shell: apt-get install -y oracle-java8-installer
  sudo: yes
